name: test-reusable
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      images:
        required: true
        type: string
jobs:
  t:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJSON(inputs.images) }}
    steps:
      - run: echo "suffix=${{ matrix.image.suffix }}"
